<a href="https://colab.research.google.com/github/Dvados/NM/blob/main/%D0%9B%D1%802.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота №2 студента групи АнД-31 Тищенко Владислава

In [2]:
import tensorflow as tf
import numpy as np


print(tf.__version__)

scalar = tf.constant(7)
print(scalar)
print(scalar.ndim)

# vector
vector = tf.constant([10, 10])
print(vector)
print(vector.ndim)

# matrix
matrix = tf.constant([[1, 2],
                      [3, 4]], dtype = tf.float16)
print(matrix)
print(matrix.ndim)

# tensor
tensor = tf.constant([[[1, 2],
                      [3, 4]],
                     
                     [[5, 6],
                      [7, 8]],
                     
                     [[9, 10],
                      [11, 12]]])
print(tensor)
print(tensor.ndim)

changeable_tensor = tf.Variable([10, 7])
print(changeable_tensor)
changeable_tensor[0].assign(7)
print(changeable_tensor)

# random
random_t = tf.random.Generator.from_seed(42) 
random_t = random_t.normal(shape=(5, 5))  
print(random_t)

# shuffle
tf.random.shuffle(random_t)

ones = tf.ones(shape=(3,2,2))
print(ones)


tensor = tf.random.normal(shape=(4, 4, 4, 4, 3))

print('shape ',tensor.shape)
print('rank ',tensor.ndim)
print('size ', tf.size(tensor).numpy())
print('elements of 0 axis ', tensor.shape[0])


print(tensor[:2, :2, :2, :2, :2])
# ten = tensor[..., tf.newaxis]
# print(ten)


tensor = tf.Variable([[2, 10],
                     [14, 22]])

print('+ \n', tensor + 15)
print('* \n',tensor * 3)
print('- \n',tensor - 10)
print()

print('matrix \n', tf.matmul(tensor, tensor))
tensor_1 = tf.constant([[1,2,3],
                        [4,10,1]])
mult = tensor @ tensor_1
print('@ \n', mult)
print('transpose \n', tf.transpose(mult))
print('reshape \n', tf.reshape(mult, shape=(3, 2)))



print(tensor)


# np array to tensor
np_array = np.arange(1,17)
tensor = tf.constant(np_array, shape=(2, 2, 4))

print(np_array)
print(tensor, type(tensor))
print()

# tensor ty np
t = tf.constant([[1, 2],
                 [3, 4]])
arr = np.array(t)
# arr = t.numpy()
print(arr, type(arr))

2.8.0
tf.Tensor(7, shape=(), dtype=int32)
0
tf.Tensor([10 10], shape=(2,), dtype=int32)
1
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float16)
2
tf.Tensor(
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]], shape=(3, 2, 2), dtype=int32)
3
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>
tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026 -1.2573844  -0.23193763]
 [-1.8107855   0.09988727 -0.50998646 -0.7535805  -0.57166284]
 [ 0.1480774  -0.23362993 -0.3522796   0.40621263 -1.0523509 ]
 [ 1.2054597   1.6874489  -0.4462975  -2.3410842   0.99009085]
 [-0.0876323  -0.635568   -0.6161736  -1.9441465  -0.48293006]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]], shape=(3, 2, 2), dtype=float32)
shape  (4, 4, 4, 4, 3)
rank  5
size  768
elements of 0 axis  4
tf.Tensor(
[[[[[-0.18603948 -0.5562171